### PR TITLE
Minor fixes to the Solana library

### PR DESCRIPTION
**Pull request by LucasSte**
I fixed an incorrect comment and a wrong index when encoding data.

### CODE REVIEW

**Review by seanyoung — CHANGES_REQUESTED** [review]
What about the other problems in this file? Why only fix two issues?

**Comment by LucasSte** [comment]
> What about the other problems in this file? Why only fix two issues?

The other problems require a separate PR with proper testing. These two were quick to fix.

**Comment by seanyoung** [comment]
Line 279 does not need a test

**Comment by LucasSte** [comment]
> Line 279 does not need a test

Is this the line you are talking about?
https://github.com/hyperledger/solang/blob/9ce88f2bb97aae9339b14715cc4b53b16fe31f90/solana-library/spl_token.sol#L279

**Comment by seanyoung** [comment]
> @seanyoung I've updated the writer flag in the transfer function as well. I am quite sure you suggested me a way to test this, but I can't recall all the details. Can you refresh my memory?

You've already done this by changing the `is_writable` flag in the `token.spec.ts`.

The burn function also wants `is_writable: true` for the `is_signer: true`. Is that correct?

**Comment by LucasSte** [comment]
> The burn function also wants `is_writable: true` for the `is_signer: true`. Is that correct?

Now that you asked, I decided to re-check every instruction in SPL-Token. Both `burn` and `mint_to` had incorrect writable booleans.

**Review by seanyoung — APPROVED** [review]

**Pull request merged**
