### PR TITLE
[Fix] Removing the duplicate code.

### PR DESCRIPTION
**Pull request by anmode**
fix: #1261

Just wanna know If I am going in the right direction or not. Please guide me so I'll then fix other parts as I am trying to understand the codebase too.

### CODE REVIEW

**Comment by xermicus** [comment]
Hi @anmode, thanks for the pull request, appreciate your request for early feedback :+1: 

I really don't like such a macro just to spare us very few lines of codes. The only thing this does is adding up to the maintenance burden. Also, please try to use functions, preferably implementations for enums / structs, instead of macros if  possible. 

If you still want to go for the first case, I have some suggestions (they might apply for other cases too).

The first match arm could be rewritten as follows:
```rust
            Type::StorageRef(immutable, r_ty) => match context.function_no {
                Some(function_no) if *immutable && !ns.functions[function_no].is_constructor() => {
                    diagnostics.push(Diagnostic::error(
                        *loc,
                        "cannot assign to immutable outside of constructor".to_string(),
                    ));
                    Err(())
                }
                _ => Ok(Expression::Assign {
                    loc: *loc,
                    ty: *r_ty.clone(),
                    left: Box::new(var),
                    right: Box::new(val.cast(&right.loc(), r_ty, true, ns, diagnostics)?),
                }),
            },
```

A further improvement could be to avoid constructing the error message twice. To achieve that you can offload it into a `OnceCell`.

Additionally, in this file there are a lot of places where a `diagnostic.push` is followed by `Err()` or `return Err(())`. This could  be offloaded to a helper function instead.

**Comment by LucasSte** [comment]
> Hi @anmode, thanks for the pull request, appreciate your request for early feedback 👍
> 
> I really don't like such a macro just to spare us very few lines of codes. The only thing this does is adding up maintenance burden. Also, please try to use functions, preferably implementations for enums / structs, instead of macros if possible.
> 
> If you still want to go for the first case in that issue, I have some suggestions (they might apply for other cases too).
> 
> The first match arm could be rewritten as follows, which basically removes the duplicated lines. This would also improve readability and gets rid of the triple nested `if` statement:
> 
> ```rust
>             Type::StorageRef(immutable, r_ty) => match context.function_no {
>                 Some(function_no) if *immutable && !ns.functions[function_no].is_constructor() => {
>                     diagnostics.push(Diagnostic::error(
>                         *loc,
>                         "cannot assign to immutable outside of constructor".to_string(),
>                     ));
>                     Err(())
>                 }
>                 _ => Ok(Expression::Assign {
>                     loc: *loc,
>                     ty: *r_ty.clone(),
>                     left: Box::new(var),
>                     right: Box::new(val.cast(&right.loc(), r_ty, true, ns, diagnostics)?),
>                 }),
>             },
> ```
> 
> A further improvement could be to avoid constructing the same error message twice. To achieve that you can offload it into a `OnceCell`.
> 
> Furthermore, in this file there are a lot of places where a `diagnostic.push` is followed by `Err()` or `return Err(())`. This could be offloaded to a helper function instead.

The idea of removing repeated code is to decrease maintenance. If we have to fix the logic in this section, we better fix it in a single place, rather than having to find all occurrences of it in the code. The code you suggested will still repeat the same logic and the same error message in two different places.

**Comment by xermicus** [comment]
On a very quick glance it looks like you can implement a method on `Type` called something like `get_assign_type`. It would return the type (`r_ty` in the current code) if it is allowed, otherwise `Err(()))` out and fill in the diagnostics. Then you'll be able to remove the two outer match statements concerned by this completely (which would remove quite more duplicated code than the IDE detected first hand).

**Comment by anmode** [comment]
> I agree with @LucasSte, there is room for improvement here. If you want you are welcome to proceed. On a very quick glance it looks like you can implement a method on `Type` called something like `get_assign_type`. It would return the type (`r_ty` in the current code) if it is allowed, otherwise `Err(())` out and fill in the diagnostics. Then you'll be able to remove the two outer match statements concerned by this completely (which would remove quite more duplicated code than the IDE detected first hand).

oh okay got that!! Thanks... One more thing. My IDE does not detect duplicate code lol. how to make my IDE of capable detecting duplicate code? I'm using VS code.

**Comment by xermicus** [comment]
> oh okay got that!! Thanks... One more thing. My IDE does not detect duplicate code lol. how to make my IDE of capable detecting duplicate code? I'm using VS code.

Ask ChatGPT :shrug: Jokes aside, it's probably the JetBrains stuff that detects this

**Comment by anmode** [comment]
> > oh okay got that!! Thanks... One more thing. My IDE does not detect duplicate code lol. how to make my IDE of capable detecting duplicate code? I'm using VS code.
> 
> Ask ChatGPT 🤷 Jokes aside, it's probably the JetBrains stuff that detects this

ohh okayy 😂

**Comment by anmode** [comment]
Just to clarify! so i can make type like this?? and this would help me to simplify `match &var_ty `
```
impl Type {
    fn get_rh_assign_type(&self, ns: &Namespace, diagnostics: &mut Vec<Diagnostic>) -> Result<Type, ()> {
        match self {
            Type::Bytes(_) | Type::Int(_) | Type::Uint(_) => Ok(self.clone()),
            Type::Ref(r_ty) => match r_ty.as_ref() {
                Type::Bytes(_) | Type::Int(_) | Type::Uint(_) => Ok(self.clone()),
                _ => {
                    diagnostics.push(Diagnostic::error(
                        loc,
                        format!("assigning to incorrect type {}", r_ty.to_string(ns)),
                    ));
                    Err(())
                }
            },
            Type::StorageRef(immutable, r_ty) => {
                if *immutable {
                    if let Some(function_no) = context.function_no {
                        if !ns.functions[function_no].is_constructor() {
                            diagnostics.push(Diagnostic::error(
                                *loc,
                                "cannot assign to immutable outside of constructor".to_string(),
                            ));
                            return Err(());
                        }
                    }
                }

                match r_ty.as_ref() {
                    Type::Bytes(_) | Type::Int(_) | Type::Uint(_) => Ok(self.clone()),
                    _ => {
                        diagnostics.push(Diagnostic::error(
                            loc,
                            format!("assigning to incorrect type {}", r_ty.to_string(ns)),
                        ));
                        Err(())
                    }
                }
            },
            _ => {
                diagnostics.push(Diagnostic::error(
                    loc,
                    "expression is not assignable".to_string(),
                ));
                Err(())
            }
        }
    }
}

**Comment by xermicus** [comment]
Yes this looks like its going into the right direction.

**Comment by xermicus** [comment]
@anmode looks like your PR got stale, hence I'm closing it. Just reply here if you planned to drive this forward within a reasonable time.

**Comment by anmode** [comment]
Hii @xermicus ..so sorry actually my end semester arrives in the middle of..
Those will be completed by 25th of may. I'm interested in solving this issue. I'll continue this.
Thanks

**Comment by xermicus** [comment]
Fine by me

**Comment by xermicus** [comment]
This PR has been stale for a while now; if you still want to finish it please just ping me here

**Pull request closed without merging**
