### PR TITLE
Add check for SPDX headers

### PR DESCRIPTION
**Pull request by seanyoung**
Signed-off-by: Sean Young <sean@mess.org>

### CODE REVIEW

**Comment by seanyoung** [comment]
@LucasSte I'll merge this after your borsh encoding pr

**Review by xermicus — APPROVED** [review]
Neat idea, LGTM!

**Review by LucasSte — APPROVED** [review]

**Comment by LucasSte** [comment]
> @LucasSte I'll merge this after your borsh encoding pr

I'm just waiting @xermicus' approval

**Comment by xermicus** [comment]
> > @LucasSte I'll merge this after your borsh encoding pr
> 
> I'm just waiting for @xermicus' approval

done :heavy_check_mark:

**Pull request merged**
