### PR TITLE
Bump inkwell and other dependencies

### PR DESCRIPTION
**Pull request by seanyoung**
- inkwell 0.1.0 has been released, which breaks the build

Signed-off-by: Sean Young <sean@mess.org>

### CODE REVIEW

**Comment by xermicus** [comment]
Can the clippy stuff wait for #1128 to go in first?

**Comment by seanyoung** [comment]
> Can the clippy stuff wait for #1128 to go in first?

Sure it can. Why would that be better?

**Comment by seanyoung** [comment]
> Can the clippy stuff wait for #1128 to go in first?

I've decided to split this PR because the clippy changes are a distinct change anyway. Now this PR is only the crate bumps.

**Comment by seanyoung** [comment]
See https://github.com/hyperledger/solang/pull/1136 for the clippy changes. This PR will need to go on first because I think the build is broken right now.

**Comment by xermicus** [comment]
Awesome, thanks!

**Review by xermicus — APPROVED** [review]
LGTM

**Review by LucasSte — APPROVED** [review]

**Pull request merged**
