### PR TITLE
Ensure that only the last instruction is an edge

### PR DESCRIPTION
**Pull request by seanyoung**
This adds a check on the CFG ensuring that only the last instruction does control flow.

### CODE REVIEW

**Comment by seanyoung** [comment]
@LucasSte the yul code has `is_reachable()` and `is_next_reachable()`. Is there a distinction?

**Review by xermicus — APPROVED** [review]
LGTM

**Comment by LucasSte** [comment]
> @LucasSte the yul code has `is_reachable()` and `is_next_reachable()`. Is there a distinction?

Yes, there is. `is_reachable` tells if the block is reachable (i.e. there exists a code path from entry to this block). `is_next_reachable` determines if this block leads to another one. If the last instruction of a block is, for instance, an `assert-failure` or a `return`, `is_reachable` can be true, but `is_next_reachable` will be false. This way, I know that I should not add any new instructions to the block (e.g. a `Instr::Branch`). Check this example:

```solidity
for(uint32 i=0; i<40; i++) {
    if(condition) {
         return i; // There is no need to add a `Instr::Branch` here, because we are returning, so `is_next_reachable` is false.
    }
}
```

**Comment by seanyoung** [comment]
Replaced by https://github.com/hyperledger/solang/pull/1260

**Pull request closed without merging**
