### PR TITLE
Add debug implementations required to print Namespace

### PR DESCRIPTION
**Pull request by chioni16**
Derive `Debug` implementations for structs and enums required to print `struct Namespace`. This is of use when one needs to print `Namespace` struct for debugging purposes.

### CODE REVIEW

**Review by xermicus — APPROVED** [review]

**Review by seanyoung — APPROVED** [review]

**Comment by LucasSte** [comment]
We don't actually need to print these structs during runtime, so adding the `#[derive(Debug)]` attribute creates overhead code that we don't use.
What do you think of enabling it only for debug builds?

https://users.rust-lang.org/t/will-derive-debug-be-compiled-in-release-build/30388

**Comment by chioni16** [comment]
> We don't actually need to print these structs during runtime, so adding the `#[derive(Debug)]` attribute creates overhead code that we don't use. What do you think of enabling it only for debug builds?
> 
> https://users.rust-lang.org/t/will-derive-debug-be-compiled-in-release-build/30388

Yes, that's better. Thanks for the suggestion!

**Comment by seanyoung** [comment]
@LucasSte what overhead are you concerned about? I does not increase code size (according to `cargo build --release` testing). You're suggesting extra code complexity, what does buy ys?

**Comment by xermicus** [comment]
If this compiles to dead code, why would it end up in the final binary? I'd expect  dead code elimination to kick it out. I'd expect guarding these derives with `cfg_attr` to improve compile time of solang itself, however I'm not too worried about a few additional `Debug` derives

**Comment by LucasSte** [comment]
> If this compiles to dead code, why would it end up in the final binary? I'd expect dead code elimination to kick it out. I'd rather expect guarding these derives with `cfg_attr` to improve compile time of solang itself, however I'm not too worried about a few additional `Debug` derives

I assumed it adds code to our binary from this question: https://users.rust-lang.org/t/will-derive-debug-be-compiled-in-release-build/30388, but I did not investigate further.

**Pull request merged**
