### PR TITLE
Remove non-idiomatic use of LinkedList

### PR DESCRIPTION
**Pull request by seanyoung**
See the note here:

https://doc.rust-lang.org/std/collections/struct.LinkedList.html

### CODE REVIEW

**Review by LucasSte — APPROVED** [review]
Have you run any benchmark?

**Comment by seanyoung** [comment]
> Have you run any benchmark?

What's your concern?

**Review by xermicus — APPROVED** [review]

**Comment by LucasSte** [comment]
> > Have you run any benchmark?
> 
> What's your concern?

I was curious if these changes provided any speedup in the compiler.

**Comment by seanyoung** [comment]
> > > Have you run any benchmark?
> > 
> > 
> > What's your concern?
> 
> I was curious if these changes provided any speedup in the compiler.

I didn't run any benchmarks. I suspect there little difference even in a micro-benchmark, and no difference in the overall compiler speed.

**Pull request merged**
