### PR TITLE
Unify `external_call` and `create_contract` on Solana

### PR DESCRIPTION
**Pull request by LucasSte**
`create_contract` and `external_call` have basically the same meaning on Solana, so I united the functions we have in `solana.c`.

This is part of my task to improve the account management on Solana. Please, read my task list #1251 To understand what I am trying to achieve.

### CODE REVIEW

**Review by seanyoung — APPROVED** [review]
Nice catch.

Please remove all the changed `.bc` files which do not matter. For example this is Solana specific so no wasm file needs to change.

**Review by xermicus — APPROVED** [review]
LGTM

**Comment by LucasSte** [comment]
> Please remove all the changed `.bc` files which do not matter. For example this is Solana specific so no wasm file needs to change.

Ok, I'll remove them. Just out of curiosity, why do we maintain these compiled filed in the repo if we build them whenever we run `cargo build`?

**Comment by seanyoung** [comment]
> Ok, I'll remove them. Just out of curiosity, why do we maintain these compiled files in the repo if we build them whenever we run `cargo build`?

They don't get built by `cargo build`. It might be possible to build them in `build.rs`. That would also remove the need for a `Makefile`.

I think it's a quick hack I did once upon a time, because I was not sure how to do this, and it has been fixed.

**Pull request merged**
